-- MySQL Script generated by MySQL Workbench
-- Sat Feb  9 14:29:04 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ppmtool_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ppmtool_db` ;

-- -----------------------------------------------------
-- Schema ppmtool_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppmtool_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ppmtool_db` ;

-- -----------------------------------------------------
-- Table `ppmtool_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`user` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`user` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_lqjrcobrh9jc8wpcar64q1bfh` (`user_name` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`project` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`project` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `end_date` DATETIME(6) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(5) NULL DEFAULT NULL,
  `project_leader` VARCHAR(255) NULL DEFAULT NULL,
  `project_name` VARCHAR(255) NULL DEFAULT NULL,
  `start_date` DATETIME(6) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `user_id` BIGINT(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_nh7jg4qyw1dm5y0bn2vwoq6v2` (`project_identifier` ASC),
  INDEX `FKo06v2e9kuapcugnyhttqa1vpt` (`user_id` ASC),
  CONSTRAINT `FKo06v2e9kuapcugnyhttqa1vpt`
    FOREIGN KEY (`user_id`)
    REFERENCES `ppmtool_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`backlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`backlog` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`backlog` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ptsequence` INT(11) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(255) NULL DEFAULT NULL,
  `project_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKl9uchve1jja83kpywpr72gi8k` (`project_id` ASC),
  CONSTRAINT `FKl9uchve1jja83kpywpr72gi8k`
    FOREIGN KEY (`project_id`)
    REFERENCES `ppmtool_db`.`project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`project_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`project_task` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`project_task` (
  `id` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `acceptance_criteria` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `due_date` DATETIME(6) NULL DEFAULT NULL,
  `priority` INT(11) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(255) NULL DEFAULT NULL,
  `project_sequence` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `summary` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `backlog_id` BIGINT(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_lk2ru5up8ilfm5wkq7wp6rtce` (`project_sequence` ASC),
  INDEX `FKnhbtfc4k2v2fsl0s3rm7uc7w3` (`backlog_id` ASC),
  CONSTRAINT `FKnhbtfc4k2v2fsl0s3rm7uc7w3`
    FOREIGN KEY (`backlog_id`)
    REFERENCES `ppmtool_db`.`backlog` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
