-- MySQL Script generated by MySQL Workbench
-- Sat Feb  2 20:15:05 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema ppmtool_db
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `ppmtool_db` ;

-- -----------------------------------------------------
-- Schema ppmtool_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ppmtool_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `ppmtool_db` ;

-- -----------------------------------------------------
-- Table `ppmtool_db`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`user` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `created_at` DATETIME NULL DEFAULT NULL,
  `full_name` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `user_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_user_name` (`user_name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`project`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`project` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`project` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `project_name` VARCHAR(45) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(45) NULL DEFAULT NULL,
  `description` VARCHAR(45) NULL DEFAULT NULL,
  `start_date` DATETIME NULL DEFAULT NULL,
  `end_date` DATETIME NULL DEFAULT NULL,
  `created_at` DATETIME NULL DEFAULT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `project` INT(11) NULL DEFAULT NULL,
  `project_leader` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_project_identifier` (`project_identifier` ASC),
  INDEX `FK_project_idx` (`project` ASC),
  INDEX `FK_user_id` (`user_id` ASC),
  CONSTRAINT `FK_project_backlog_id`
    FOREIGN KEY (`project`)
    REFERENCES `ppmtool_db`.`backlog` (`id`),
  CONSTRAINT `FK_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `ppmtool_db`.`user` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`backlog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`backlog` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`backlog` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `ptsequence` INT(11) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(45) NULL DEFAULT NULL,
  `project_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_project_idx` (`project_id` ASC),
  CONSTRAINT `FK_project_id`
    FOREIGN KEY (`project_id`)
    REFERENCES `ppmtool_db`.`project` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `ppmtool_db`.`project_task`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `ppmtool_db`.`project_task` ;

CREATE TABLE IF NOT EXISTS `ppmtool_db`.`project_task` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `acceptance_criteria` VARCHAR(255) NULL DEFAULT NULL,
  `created_at` DATETIME(6) NULL DEFAULT NULL,
  `due_date` DATETIME(6) NULL DEFAULT NULL,
  `priority` INT(11) NULL DEFAULT NULL,
  `project_identifier` VARCHAR(255) NULL DEFAULT NULL,
  `project_sequence` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `summary` VARCHAR(255) NULL DEFAULT NULL,
  `updated_at` DATETIME(6) NULL DEFAULT NULL,
  `backlog_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_project_sequence` (`project_sequence` ASC),
  INDEX `FK_backlog_id` (`backlog_id` ASC),
  CONSTRAINT `FK_backlog_id`
    FOREIGN KEY (`backlog_id`)
    REFERENCES `ppmtool_db`.`backlog` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
